
name: "Dev deployment"

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is opened against the repo's
# main branch or an existing pull request's head branch is updated.
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Databricks Asset Bundle
        run: databricks bundle deploy
        working-directory: .
        env:          
          DATABRICKS_BUNDLE_ENV: dev
          DATABRICKS_CLIENT_ID: ${{ secrets.SP_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SP_SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.SP_TENANT }}
          DATABRICKS_HOST: ${{ secrets.DB_HOST }}

  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest
    needs:
      - deploy

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run Databricks pipeline
        run: databricks bundle run ae_sim_pipeline --refresh-all
        working-directory: .
        env:
          DATABRICKS_BUNDLE_ENV: dev
          DATABRICKS_CLIENT_ID: ${{ secrets.SP_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SP_SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.SP_TENANT }}
          DATABRICKS_HOST: ${{ secrets.DB_HOST }}
